export default {
  medicine: {
    "Covid Medicines": ["Covid Medicines", "Medicines"],
    "Liposomal Amphotericin B": [
      "Liposomal Amphotericin B",
      "Liposomal",
      "Amphotericin",
      "Amphonex",
      "Ampho",
      "Amphotret",
      "Amphomul",
      "Amfoteral",
      "Levicare",
      "Ambilon",
      "Phosome",
      "Gufisome",
      "Ampholip",
    ],
    Tocilizumab: ["Tocilizumab", "Actemra", "Tociliizumumab"],
    "Buprenorphine Transdermal": [
      "Buprenorphine Transdermal",
      "Buprenorphine",
      "Transdermal",
      "Buvalor",
    ],
    "Baricitinib Olumiant": ["Baricitinib Olumiant", "Baricitinib"],
    Fabiflu: ["Fabiflu", "Fabi flu"],
    Favipivavir: ["Favipivavir", "Feravir"],
    Xarelto: ["Xarelto"],
    "Sodium Lactate": ["Sodium Lactate", "Axaring-RL"],
    "Sodium Chloride": ["Sodium Chloride"],
    Doxycycline: ["Doxycycline", "Doxy Pure", "DoxyPure"],
    "Piperacilin Tazobactum": [
      "Piperacilin Tazobactum",
      "Piperacilin",
      "Tazobactum",
      "Tazact",
    ],
    Pantoprazole: ["Pantoprazole", "Pansec"],
    "Ascorbic Acid": ["Ascorbic Acid", "Vitcee"],
    "Posaconazole Gastro Resistant": [
      "Posaconazole Gastro Resistant",
      "Posaconazole",
    ],
    Anidulafungin: ["Anidulafungin", "Eraxis"],
    Meropenem: ["Meropenem", "Opipenem"],
    "Doxorubicim Hydrochloride Liposome": [
      "Doxorubicim Hydrochloride Liposome",
      "Lipodox",
    ],
    Deflazacort: ["Deflazacort"],
    "Deoxy-D-Glucose": ["Deoxy-D-Glucose", "Deoxy D Glucose", "2DG", "2-DG"],
    Zinc: ["Zinc", "Zincovit"],
    "Vitamin C": ["Vitamin C"],
    Azithromycin: ["Azithromycin"],
    Bevacuzimab: ["Bevacuzimab", "Bevancizumab"],
    "Methyl Prednisolone": ["Methyl Prednisolone"],
    Enoxaparin: ["Enoxaparin"],
    Posatral: ["Postral"],
    Medrol: ["Medrol", "Metni"],
    Remdesivir: ["Remdesivir"],
  },
  food: {
    Food: ["Food", "Meals", "Langar", "Tiffin", "Cooked meals"],
    "Dry Ration": ["Dry Ration"],
  },
  ambulance: {
    Ambulance: ["Ambulance", "Shift Patient", "Move Patient"],
  },
  oxygen: {
    "Oxygen Cans": ["Oxygen Cans", "Cans", "Cannister"],
    "Oxygen Cylinders": ["Oxygen Cylinders", "Cylinder", "Medical Oxygen"],
    "Oxygen Concentrators": ["Oxygen Concentrators", "Concentrator"],
    "Oxygen Refill": ["Oxygen Refill", "Refill", "Oxygen Gas", "Refilling"],
    "Oxygen Regulator": [
      "Oxygen Regulator",
      "Oxygen Kit",
      "Oxygen Cylinder Kit",
    ],
    Oximeter: ["Oximeter", "Pulse Oximeter"],
    Respirometer: ["Respirometer"],
  },
  bed: {
    "Oxygen Beds": ["Oxygen Beds"],
    "ICU Beds": ["ICU Beds"],
    "Home ICU": ["Home ICU", "ICU Setup"],
    Ventilators: ["Ventilators", "with venti"],
  },
  therapy: {
    Plasma: ["Plasma", "Plazma"],
    ECMO: ["ECMO"],
  },
  bloodkeywords: [
    "any group",
    "blood group",
    "normal blood",
    "plasma",
    "blood",
    "platelet",
  ],
  senderkeywords: [
    "dm me",
    "message me",
    "pls call me",
    "help me",
    "i need",
    "any leads",
    "any lead for",
    "my friend",
    "ping me",
    "pm me",
    "pls pm",
    "reach out to me",
    "my brother",
    "my mother",
    "my father",
    "my wife",
    "my husband",
    "we need",
    "tell me",
    "let me know",
    "i know someone",
    "my elder",
    "my younger",
    "my cousin",
    "my uncle",
    "my aunt",
    "reply",
    "for a friend",
    "we'll collect",
  ],
  cities: [
    "Delhi",
    "Bangalore",
    "Mumbai",
    "Pune",
    "Thane",
    "Nagpur",
    "Lucknow",
    "Chennai",
    "Kolkata",
    "Ahmedabad",
    "Jaipur",
    "Telangana",
    "Indore",
    "Bhopal",
    "Nashik",
    "Amritsar",
    "Assam",
    "Hyderabad",
    "Visakhapatnam",
    "Ajmer",
    "Kota",
    "Bareilly",
    "Gurgaon",
    "Noida,",
    "Bhilwara",
    "Agra",
    "Kanpur",
    "Patna",
    "Udaipur",
    "Akola,",
    "Abohar",
    "Adilabad",
    "Agar malwa",
    "Agartala",
    "Ahmadnagar",
    "Ahmednagar",
    "Aizawl",
    "Akola",
    "Alappuzha",
    "Aligarh",
    "Alipurduar",
    "Alirajpur",
    "Allahabad",
    "Almora",
    "Alwar",
    "Amaravati",
    "Ambala",
    "Ambedkar nagar",
    "Ambikapur",
    "Amethi",
    "Amravati",
    "Amreli",
    "Amroha",
    "Anand",
    "Anantapur",
    "Anantnag",
    "Angul",
    "Anjaw",
    "Anuppur",
    "Araria",
    "Aravalli",
    "Ariyalur",
    "Arwal",
    "Asansol",
    "Ashoknagar",
    "Auraiya",
    "Aurangabad",
    "Ayodhya",
    "Azamgarh",
    "Bagalkot",
    "Bagalkote",
    "Bageshwar",
    "Baghpat",
    "Bahraich",
    "Bakshpur",
    "Balaghat",
    "Balangir",
    "Balasore",
    "Ballari",
    "Ballia",
    "Balod",
    "Baloda bazar",
    "Balrampur",
    "Bamanpuri",
    "Bametara",
    "Banaskantha",
    "Banda",
    "Bandipora",
    "Banka",
    "Bankura",
    "Banswara",
    "Barabanki",
    "Baramula",
    "Baramulla",
    "Baran",
    "Barddhaman",
    "Bargarh",
    "Barmer",
    "Barnala",
    "Barwani",
    "Bastar",
    "Basti",
    "Bathinda",
    "Beed",
    "Begusarai",
    "Belagavi",
    "Belgaum",
    "Bellary",
    "Bengaluru",
    "Bengaluru rural",
    "Bengaluru urban",
    "Betul",
    "Bhadohi",
    "Bhadrak",
    "Bhagalpur",
    "Bhandara",
    "Bharatpur",
    "Bharauri",
    "Bharuch",
    "Bhatpara",
    "Bhavnagar",
    "Bhilai",
    "Bhind",
    "Bhiwandi",
    "Bhiwani",
    "Bhojpur",
    "Bhubaneshwar",
    "Bhuj",
    "Bhusaval",
    "Bidar",
    "Bijapur",
    "Bijnor",
    "Bikaner",
    "Bilaspur",
    "Birbhum",
    "Bokaro",
    "Botad",
    "Boudh",
    "Brahmapur",
    "Bsf camp",
    "Budaun",
    "Budgam",
    "Bulandshahr",
    "Buldhana",
    "Bundi",
    "Burhanpur",
    "Buxar",
    "Calicut",
    "Capital complex",
    "Chamarajanagara",
    "Chamba",
    "Chamoli",
    "Champawat",
    "Champhai",
    "Chanda",
    "Chandauli",
    "Chandigarh",
    "Chandrapur",
    "Changlang",
    "Charkhi dadri",
    "Chatra",
    "Chengalpattu",
    "Chhatarpur",
    "Chhindwara",
    "Chhota udaipur",
    "Chikka mandya",
    "Chikkaballapura",
    "Chikkamagaluru",
    "Chirala",
    "Chirawa",
    "Chitradurga",
    "Chitrakoot",
    "Chittoor",
    "Chittorgarh",
    "Churu",
    "Coimbatore",
    "Cooch behar",
    "Cuddalore",
    "Cuttack",
    "Dadranagar haveli",
    "Dahod",
    "Dakshin bastar dantewada",
    "Dakshin dinajpur",
    "Dakshina kannada",
    "Daman",
    "Damoh",
    "Dang",
    "Darbhanga",
    "Darjeeling",
    "Datia",
    "Dausa",
    "Davanagere",
    "Davangere",
    "Dehradun",
    "Deogarh",
    "Deoghar",
    "Deoria",
    "Devbhumi dwarka",
    "Dewas",
    "Dhalai",
    "Dhamtari",
    "Dhanbad",
    "Dhar",
    "Dharmapuri",
    "Dharwad",
    "Dhenkanal",
    "Dholpur",
    "Dhule",
    "Dibrugarh",
    "Dimapur",
    "Dindigul",
    "Dindori",
    "Dispur",
    "Diu",
    "Doda",
    "Dumka",
    "Dungarpur",
    "Durg",
    "East champaran",
    "East garo hills",
    "East godavari",
    "East jaintia hills",
    "East kameng",
    "East khasi hills",
    "East siang",
    "East singhbhum",
    "Ernakulam",
    "Erode",
    "Etah",
    "Etawah",
    "Evacuees",
    "Faridabad",
    "Faridkot",
    "Farrukhabad",
    "Fatehabad",
    "Fatehgarh sahib",
    "Fatehpur",
    "Fazilka",
    "Ferozepur",
    "Firozabad",
    "Foreign evacuees",
    "Fyzabad",
    "Gadag",
    "Gadchiroli",
    "Gajapati",
    "Ganderbal",
    "Gandhinagar",
    "Ganganagar",
    "Gangtok",
    "Ganjam",
    "Garhwa",
    "Gariaband",
    "Gaurela pendra marwahi",
    "Gautam buddha nagar",
    "Gaya",
    "Ghandinagar",
    "Ghaziabad",
    "Ghazipur",
    "Gir somnath",
    "Giridih",
    "Goa",
    "Godavari",
    "Godda",
    "Gomati",
    "Gonda",
    "Gondia",
    "Gopalganj",
    "Gopalpur",
    "Gorakhpur",
    "Gulbarga",
    "Gumla",
    "Guna",
    "Guntur",
    "Gurdaspur",
    "Gurugram",
    "Guwahati",
    "Gwalior",
    "Haldia",
    "Hamirpur",
    "Hanumangarh",
    "Haora",
    "Hapur",
    "Harda",
    "Hardoi",
    "Haridwar",
    "Haripur",
    "Hassan",
    "Hata",
    "Hathras",
    "Haveri",
    "Hazaribagh",
    "Himachal",
    "Hindupur",
    "Hingoli",
    "Hisar",
    "Hnahthial",
    "Hooghly",
    "Hoshangabad",
    "Hoshiarpur",
    "Hospet",
    "Howrah",
    "Hubli",
    "Idukki",
    "Imphal",
    "Italians",
    "Itanagar",
    "Jabalpur",
    "Jagatsinghpur",
    "Jaisalmer",
    "Jajpur",
    "Jalandhar",
    "Jalaun",
    "Jalgaon",
    "Jalna",
    "Jalore",
    "Jalpaiguri",
    "Jammu",
    "Jamnagar",
    "Jamshedpur",
    "Jamtara",
    "Jamui",
    "Janjgir",
    "Janjgir champa",
    "Jashpur",
    "Jaunpur",
    "Jehanabad",
    "Jhabua",
    "Jhajjar",
    "Jhalawar",
    "Jhansi",
    "Jhargram",
    "Jharsugda",
    "Jharsuguda",
    "Jhunjhunu",
    "Jind",
    "Jodhpur",
    "Jorhat",
    "Junagadh",
    "Kabeerdham",
    "Kadapa",
    "Kagaznagar",
    "Kaimur",
    "Kaithal",
    "Kakinada",
    "Kalaburagi",
    "Kalahandi",
    "Kalimpong",
    "Kallakurichi",
    "Kalyan",
    "Kamle",
    "Kancheepuram",
    "Kandhamal",
    "Kangra",
    "Kannauj",
    "Kannur",
    "Kanpur dehat",
    "Kanpur nagar",
    "Kanyakumari",
    "Kapurthala",
    "Karaikal",
    "Karauli",
    "Kargil",
    "Karimnagar",
    "Karnal",
    "Karur",
    "Kasaragod",
    "Kasganj",
    "Kathua",
    "Katihar",
    "Katni",
    "Kaushambi",
    "Kavaratti",
    "Khordha",
    "Kohima",
    "Kolar",
    "Kolhapur",
    "Kollam",
    "Koppal",
    "Korba",
    "Koriya",
    "Kottayam",
    "Kozhikode",
    "Krishna",
    "Krishnagiri",
    "Kurnool",
    "Kurukshetra",
    "Lakhimpur kheri",
    "Latur",
    "Ludhiana",
    "Madurai",
    "Mahasamund",
    "Malappuram",
    "Malda",
    "Mandi",
    "Mandya",
    "Mangalore",
    "Mathura",
    "Mayurbhanj",
    "Meerut",
    "Mehsana",
    "Moradabad",
    "Mungeli",
    "Murshidabad",
    "Muzaffarnagar",
    "Muzaffarpur",
    "Mysuru",
    "Nadia",
    "Nainital",
    "Nalanda",
    "Namakkal",
    "Nanded",
    "Nandurbar",
    "Nellore",
    "Nuapada",
    "Osmanabad",
    "Palakkad",
    "Palghar",
    "Pali",
    "Panaji",
    "Panchkula",
    "Panipat",
    "Parbhani",
    "Parganas",
    "Paschim bardhaman",
    "Paschim medinipur",
    "Pathanamthitta",
    "Patiala",
    "Pilani",
    "Prakasam",
    "Prayagraj",
    "Puducherry",
    "Purba bardhaman",
    "Purba medinipur",
    "Puri",
    "Purnia",
    "Raichur",
    "Raigad",
    "Raigarh",
    "Raipur",
    "Rajkot",
    "Rajnandgaon",
    "Ranchi",
    "Ranipet",
    "Ratnagiri",
    "Rohtak",
    "Saharanpur",
    "Salem",
    "Sambalpur",
    "Sangli",
    "Saran",
    "Satara",
    "Shahjahanpur",
    "Shillong",
    "Shimla",
    "Shivamogga",
    "Sikar",
    "Singhbhum",
    "Sirsa",
    "Solapur",
    "Sonipat",
    "Srikakulam",
    "Srinagar",
    "Sundargarh",
    "Surajpur",
    "Surat",
    "Surguja",
    "Thanjavur",
    "Theni",
    "Thiruvallur",
    "Thiruvananthapuram",
    "Thiruvarur",
    "Thoothukkudi",
    "Thrissur",
    "Tiruchirappalli",
    "Tirunelveli",
    "Tirupati",
    "Tiruppur",
    "Tiruvannamalai",
    "Trivandrum",
    "Tumakuru",
    "Udham singh nagar",
    "Udupi",
    "Unknown",
    "Uttar bastar kanker",
    "Uttara kannada",
    "Vadodara",
    "Vadodra",
    "Varanasi",
    "Vellore",
    "Vijayapura",
    "Vijaywada",
    "Viluppuram",
    "Virudhunagar",
    "Vizianagaram",
    "Wardha",
    "Washim",
    "Wayanad",
    "Yadgir",
    "Yamunanagar",
    "Yavatmal",
  ],
};
